Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"

  #if Vagrant.has_plugin?("vagrant-proxyconf")
  #    config.proxy.http     = "http://10.144.1.10:8080/"
  #    config.proxy.https    = "http://10.144.1.10:8080/"
  #end

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = "2048"
    vb.name = "Nokia_Warsztaty_CPP"
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    # basic, required packages
    sudo apt-get install -y make cmake clang g++ gcc valgrind git wget vim htop libboost-all-dev
    # GUI stuff - optional
    sudo apt-get install -y qtcreator kwrite openssh-server xinit xfce4

    sudo apt-get clean
  SHELL
end
